### ISSUE TITLE
Port 80 is broken

### ISSUE THREAD

**Issue by RiversideRocks** [youngchief-btw/ProxyChief#6]
`https://pr0xy1--jtnexus.repl.co:80` does not work.

**Comment by youngchief-btw** [comment]
Seems like recent updates have affected it. I will fix them soon.

**Comment by youngchief-btw** [comment]
@RiversideRocks Seems fine, I think you were trying to access port 80 using HTTPS. I will fix the listing because it has HTTPS with port 80 on it.

**Comment by RiversideRocks** [comment]
I was able to view it now! Thanks. I will close this issue now.

**Comment by youngchief-btw** [comment]
👍
